[tool.poetry]
name = "phospho"
version = "0.0.2"
description = ""
authors = ["Pierre-LouisBJT <78322686+Pierre-LouisBJT@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"
requests-mock = "^1.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
